---
# handlers file for powerdns

- name: restart powerdns authoritative
  become: yes
  service:
    name: "{{ powerdns_authoritative_service_name }}"
    state: restarted
  tags:
    - powerdns
    - authoritative

- name: reload powerdns authoritative
  become: yes
  service:
    name: "{{ powerdns_authoritative_service_name }}"
    state: reloaded
  tags:
    - powerdns
    - authoritative

- name: restart powerdns recursor
  become: yes
  service:
    name: "{{ powerdns_recursor_service_name }}"
    state: restarted
  tags:
    - powerdns
    - recursor

- name: reload powerdns recursor
  become: yes
  service:
    name: "{{ powerdns_recursor_service_name }}"
    state: reloaded
  tags:
    - powerdns
    - recursor
